/*
 * Fotos reais usadas pelos jogos.
 *
 * As URLs usam o serviço público LoremFlickr com consulta semântica e lock fixo,
 * para que cada palavra tenha uma foto correspondente e determinística.
 * A pasta lógica deste catálogo mantém todos os links em um único lugar.
 */
const photo = (query: string, lock: number) =>
  `https://loremflickr.com/320/240/${query}?lock=${lock}`

export const REAL_IMAGE_MAP: Record<string, string> = {
  // Animais
  cat: photo("cat,animal", 101), gato: photo("cat,animal", 101),
  dog: photo("dog,animal", 102), cachorro: photo("dog,animal", 102),
  rat: photo("rat,animal", 103), rato: photo("rat,animal", 103),
  cow: photo("cow,animal", 104), vaca: photo("cow,animal", 104),
  seal: photo("seal,animal", 105), foca: photo("seal,animal", 105),
  duck: photo("duck,animal", 106), pato: photo("duck,animal", 106),
  horse: photo("horse,animal", 107), camel: photo("camel,animal", 108),
  butterfly: photo("butterfly,insect", 110),
  monkey: photo("monkey,animal", 114),
  turtle: photo("turtle,animal", 112),
  elephant: photo("elephant,animal", 109),
  whale: photo("whale,animal", 111),
  giraffe: photo("giraffe,animal", 113),
  frog: photo("frog,animal", 115), macaco: photo("monkey,animal", 114), sapo: photo("frog,animal", 115),

  // Objetos e lugares
  knife: photo("kitchen,knife", 201), faca: photo("kitchen,knife", 201),
  boat: photo("boat", 202), barca: photo("boat", 202),
  door: photo("door", 203), porta: photo("door", 203),
  necklace: photo("necklace,jewelry", 204), colar: photo("necklace,jewelry", 204),
  rainbow: photo("rainbow", 205), arco: photo("rainbow", 205),
  pocket: photo("pocket,clothing", 206), bolso: photo("pocket,clothing", 206),
  stage: photo("theater,stage", 207), palco: photo("theater,stage", 207),
  window: photo("window", 208), janela: photo("window", 208),
  distaff: photo("spinning,wheel,wood", 209), roca: photo("spinning,wheel,wood", 209),
  bed: photo("bed", 210), cama: photo("bed", 210),
  suitcase: photo("suitcase", 211), mala: photo("suitcase", 211),
  room: photo("room,interior", 212), sala: photo("living,room", 212),
  book: photo("book", 213), livro: photo("book", 213), escola: photo("school,classroom", 214),
  table: photo("table", 215), mesa: photo("table", 215),
  bench: photo("bench", 216), banco: photo("bench", 216),
  box: photo("cardboard,box", 217), posse: photo("box,belongings", 217),
  ball: photo("ball", 218), bola: photo("ball", 218),
  spring: photo("metal,spring", 219), mola: photo("metal,spring", 219),
  glue: photo("glue,bottle", 220), cola: photo("glue,bottle", 220),
  vase: photo("flower,vase", 221), vasa: photo("flower,vase", 221),
  pool: photo("shallow,pool", 222), rasa: photo("shallow,pool", 222),
  plate: photo("plate", 223), prato: photo("plate", 223),
  envelope: photo("letter,envelope", 224),
  bottle: photo("water,bottle", 225),
  bicycle: photo("bicycle", 226),
  eraser: photo("eraser", 227),
  chocolate: photo("chocolate,bar", 228),
  pencil: photo("pencil", 229),
  dice: photo("dice", 230), dado: photo("dice", 230),
  lantern: photo("lantern", 231), farol: photo("lighthouse,lantern", 231),
  speaker: photo("speaker", 232),
  camera: photo("camera", 233),
  magnify: photo("magnifying,glass", 234),
  shield: photo("shield", 235),
  monster: photo("friendly,monster,toy", 236),
  blanket: photo("blanket", 237), lençol: photo("bed,sheet", 237), manta: photo("blanket", 237),
  shirt: photo("shirt", 238), gola: photo("shirt,collar", 238),
  plant: photo("green,plant", 239), planta: photo("green,plant", 239), mato: photo("grass,plants", 239), flor: photo("flower", 240),
  house: photo("house", 241), shoe: photo("shoe", 242),
  jumping: photo("child,jumping", 241), pular: photo("jumping", 241),

  // Alimentos e natureza
  apple: photo("apple,fruit", 301), maçã: photo("apple,fruit", 301),
  bread: photo("bread", 302), pão: photo("bread", 302),
  candy: photo("candy", 303), bala: photo("candy", 303),
  banana: photo("banana", 304),
  tomato: photo("tomato", 305),
  cloud: photo("cloud", 306), vapor: photo("steam,cloud", 306),
  sun: photo("sun", 307), sol: photo("sun", 307),
  fire: photo("fire", 308),
  hand: photo("hand", 309), mão: photo("hand", 309),
  heart: photo("heart", 310),
  star: photo("star", 311), estrela: photo("star", 311),
  animal: photo("farm,animal", 312), paca: photo("animal,wildlife", 312),
  airplane: photo("airplane", 313), avião: photo("airplane", 313),
  plantpot: photo("potted,plant", 314),
  bandage: photo("bandage", 315), dor: photo("bandage,first,aid", 315),
  trophy: photo("trophy", 316), fama: photo("trophy", 316),
  chess: photo("chess,piece", 317), dama: photo("chess,piece", 317),
  skull: photo("skull,decoration", 318), morte: photo("skull,decoration", 318),
  seed: photo("seed", 319), grão: photo("seed", 319),
  stick: photo("wooden,stick", 320), toco: photo("wood,log", 320),
  hole: photo("hole,ground", 321), cova: photo("hole,ground", 321),
  car: photo("car", 322), carro: photo("car", 322),
  shirt2: photo("shirt", 323),
  person: photo("person", 324), franco: photo("person", 324),
  rainbow2: photo("rainbow", 325), cor: photo("colorful,paint", 325),
  vase2: photo("vase", 326),
}
